/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2020 Intel Corporation.
 */

#ifndef __THB_PCIE_BOOT_H__
#define __THB_PCIE_BOOT_H__

#define VPUUBOOT_IMAGE_OS (0xFFFFFF4F)
#define VPUUBOOT_IMAGE_FS (0xFFFFFF46)
#define VPUUBOOT_IMAGE_DEST (0xFFFF0000)
#define VPUUBOOT_IMAGE_PART_FLASH (0xFFFFFF00)
#define VPUUBOOT_IMAGE_PART_ERASE (0xFFFFFF01)
#define VPUUBOOT_IMAGE_FLASH_GPT (0xFFFFFF02)

#define VPUUBOOT_EP_START_VAL (0x55555555)
#define VPUUBOOT_ERR_VAL (0xDEADAAAA)
#define VPUUBOOT_INVALID_IMG_VAL (0xDEADFFFF)
#define VPUUBOOT_DOWNLOAD_DONE_VAL (0xDDDDDDDD)
#define VPUUBOOT_EP_BOOT_VAL (0xBBBBBBBB)

#define VPUUBOOT_MAGIC_OFFSET (0x00)
#define VPUUBOOT_MF_READY_OFFSET (0x10)
#define VPUUBOOT_MF_LEN_OFFSET (0x14)
#define VPUUBOOT_MF_START_OFFSET (0x20)
#define VPUUBOOT_INT_EN_OFFSET (0x28)
#define VPUUBOOT_INT_MSK_OFFSET (0x2C)
#define VPUUBOOT_INT_IDENT_OFFSET (0x30)
#define VPUUBOOT_MF_OFFSET_OFFSET (0x38)
#define VPUUBOOT_MF_DEST_OFFSET (0x40)
#define VPUUBOOT_DEV_ID_OFFSET (0xC0)
#define VPUUBOOT_COMMS_BUFFER_SIZE (0xC8)
#define VPUUBOOT_MAGIC_STRING "VPUUBOOT-001"
#define VPURECOV_MAGIC_STRING "VPURECOV-001"
#define VPUUBOOT_MAGIC_SIZE (12)
#define VPUUBOOT_INT_CTX_SIZE (8)
#define MAGIC_YEAR (0x2020)
#define MAGIC_MONTH (0x06)
#define MAGIC_DAY (0x6)
#define VPUUBOOT_MAGIC_DATE ((MAGIC_YEAR << 16) | \
		(MAGIC_MONTH << 8) | MAGIC_DAY)
#define VPUUBOOT_READY_INTERRUPT (BIT(0))

struct pcie_iatu_setup_cfg {
	u32 comms_bar_size;
	char magic[VPUUBOOT_MAGIC_SIZE];
        u64 dev_id;
};

#endif /* __THB_PCIE_BOOT_H__ */
