#
# Copyright (c) 2019-2020 Intel Corporation.
#
# SPDX-License-Identifier:	GPL-2.0
#
#obj-y += soc.o
#obj-y += thb_svn.o
obj-$(CONFIG_CMD_THUNDERBAY_PCIE_BOOT) += thb_pcie_boot.o
obj-$(CONFIG_CMD_THUNDERBAY_FUSE_PROVISION) += cmd_efuse_ops.o
#obj-$(CONFIG_CMD_THUNDERBAY_CLOCK_DEBUG_CONFIG) += ma_scmi_clock_debug_config.o
