#
# Copyright (c) 2019-2020 Intel Corporation.
#
# SPDX-License-Identifier:	GPL-2.0
#
#obj-y += soc.o
#obj-y += thb_svn.o
#obj-$(CONFIG_THUNDERBAY_PCIE_EP_MISC_VPU_BOOT) += thb_pcie.o
#obj-$(CONFIG_CMD_THUNDERBAY_PCIE_BOOT) += ma_pcie_boot.o
#obj-$(CONFIG_CMD_THUNDERBAY_CLOCK_DEBUG_CONFIG) += ma_scmi_clock_debug_config.o
#obj-$(CONFIG_THUNDERBAY_PCIE_EP_MISC_VPU_BOOT) += thb_pcie.o
#obj-$(CONFIG_CMD_THUNDERBAY_PCIE_BOOT) += ma_pcie_boot.o
#obj-$(CONFIG_CMD_THUNDERBAY_CLOCK_DEBUG_CONFIG) += ma_scmi_clock_debug_config.o
