# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2019-2020 Intel Corporation

obj-$(CONFIG_ECDSA) += ecdsa-engine-uclass.o
obj-$(CONFIG_ECDSA_ENGINE_SW) += ecdsa-engine-sw.o
obj-$(CONFIG_ECDSA_ENGINE_THUNDERBAY) += thunderbay-ecdsa-engine.o
