# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2019-2020 Intel Corporation

obj-$(CONFIG_XMSS) += xmss-engine-uclass.o
obj-$(CONFIG_XMSS_ENGINE_SW) += xmss-engine-sw.o
obj-$(CONFIG_XMSS_ENGINE_THUNDERBAY) += thunderbay-xmss-engine.o
