#
# (C) Copyright 2017 Linaro
# Copyright (c) 2020 Intel Corporation
#
# Jorge Ramirez-Ortiz <jorge.ramirez-ortiz@linaro.org>
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-y	:= thb-soc.o
obj-$(CONFIG_THUNDERBAY_MEM_PROTECT) += thb-imr.o
