/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2021 Intel Corporation
 */

#ifndef _DT_BINDINGS_POWER_DOMAIN_IDS_H
#define _DT_BINDINGS_POWER_DOMAIN_IDS_H

#define PWR_DOMAIN_VCE_SLICE0 0
#define PWR_DOMAIN_VCDA_SLICE0 1
#define PWR_DOMAIN_VCDB_SLICE0 2
#define PWR_DOMAIN_VCEJ_SLICE0 3

#define PWR_DOMAIN_VCE_SLICE1 4
#define PWR_DOMAIN_VCDA_SLICE1 5
#define PWR_DOMAIN_VCDB_SLICE1 6
#define PWR_DOMAIN_VCEJ_SLICE1 7

#define PWR_DOMAIN_VCE_SLICE2 8
#define PWR_DOMAIN_VCDA_SLICE2 9
#define PWR_DOMAIN_VCDB_SLICE2 10
#define PWR_DOMAIN_VCEJ_SLICE2 11

#define PWR_DOMAIN_VCE_SLICE3 12
#define PWR_DOMAIN_VCDA_SLICE3 13
#define PWR_DOMAIN_VCDB_SLICE3 14
#define PWR_DOMAIN_VCEJ_SLICE3 15

#endif
